# Makefile for Standard C Library
#
CXX = cc64 -w -S 

all:
	cd ASSERT
	nmake /C ASSERT
	cd ..
	cd CTYPE
	nmake /C CTYPE
	cd ..
	cd ERRNO
	nmake /C ERRNO
	cd ..
	cd FLOAT
	nmake /C FLOAT
	cd ..
	cd LOCALE
	nmake /C LOCALE
	cd ..
	cd MATH
	nmake /C MATH
	cd ..
	cd SETJMP
	nmake /c SETJMP
	cd ..
	cd SIGNAL
	nmake /C SIGNAL
	cd ..
	cd STDIO
	nmake /C STDIO
	cd ..
	cd STDLIB
	nmake /C STDLIB
	cd ..
	cd STRING
	nmake /C STRING
	cd ..
	cd TIME
	nmake /C TIME
	cd ..


ASSERT:
	cd ASSERT
	nmake /C ASSERT
	cd ..
#
CTYPE:
	cd CTYPE
	nmake /C CTYPE
	cd ..
#
ERRNO:
	cd ERRNO
	nmake /C ERRNO
	cd ..
#
FLOAT:
	cd FLOAT
	nmake /C FLOAT
	cd ..
#
LOCALE:
	cd LOCALE
	nmake /C LOCALE
	cd ..
#
MATH:
	cd MATH
	nmake /C MATCH
	cd ..
#
SETJMP:
	cd SETJMP
	nmake /c SETJMP
	cd ..
#
SIGNAL:
	cd SIGNAL
	nmake /C SIGNAL
	cd ..
#
STDIO:
	cd STDIO
	nmake /C STDIO
	cd ..
#
STDLIB:
	cd STDLIB
	nmake /C STDLIB
	cd ..
#
STRING:
	cd STRING
	nmake /C STRING
	cd ..
#
TIME:
	cd TIME
	nmake /C TIME
	cd ..

clean:
	cd ASSERT
	nmake /C clean
	cd ..
	cd CTYPE
	nmake /C clean
	cd ..
	cd ERRNO
	nmake /C clean
	cd ..
	cd FLOAT
	nmake /C clean
	cd ..
	cd LOCALE
	nmake /C clean
	cd ..
	cd MATH
	nmake /C clean
	cd ..
	cd SETJMP
	nmake /C clean
	cd ..
	cd SIGNAL
	nmake /C clean
	cd ..
	cd STDIO
	nmake /C clean
	cd ..
	cd STDLIB
	nmake /C clean
	cd ..
	cd STRING
	nmake /C clean
	cd ..
	cd TIME
	nmake /C clean
	cd ..
